"""add blob_url to receipts

Revision ID: 0288ff79b7f0
Revises: 508b7e8edb15
Create Date: 2026-02-27 02:19:03.987674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0288ff79b7f0'
down_revision: Union[str, Sequence[str], None] = '508b7e8edb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('blob_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'blob_url')
    # ### end Alembic commands ###
