"""add category fields to receipt_items

Revision ID: 508b7e8edb15
Revises: 826840723f23
Create Date: 2026-02-27 00:53:21.879536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508b7e8edb15'
down_revision: Union[str, Sequence[str], None] = '826840723f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('receipt_items', sa.Column('category_source', sa.String(length=30), nullable=True))
    op.add_column('receipt_items', sa.Column('category_confidence', sa.Float(), nullable=True))
    op.add_column('receipt_items', sa.Column('categorized_at', sa.DateTime(), nullable=True))
    # op.alter_column('users', 'microsoft_id',
    #            existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'microsoft_id',
    #            existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
    #            nullable=True)
    op.drop_column('receipt_items', 'categorized_at')
    op.drop_column('receipt_items', 'category_confidence')
    op.drop_column('receipt_items', 'category_source')
    op.drop_column('receipt_items', 'category')
    # ### end Alembic commands ###
